<?php 
    session_start();
    include '../connection.php';
    include '../functions.php';
    require_once 'AuthGen/PHPGangsta/GoogleAuthenticator.php';

    $user_data = check_login($con);

    if (!class_exists('PHPGangsta_GoogleAuthenticator')) {
        class PHPGangsta_GoogleAuthenticator
        {
            public function verifyCode($secret, $otp, $tolerance = 1) { return false; }
        }
    }

    $authenticator = new PHPGangsta_GoogleAuthenticator();
    $secret = $user_data['auth_key']; //Secret key stored in the database for the user.

    if($_SERVER['REQUEST_METHOD'] == "POST")
    {
        $otp = $_POST['code'] ;//Generated by Authenticator.
        
        $tolerance = 1; //Allows codes within 30 seconds before or after the current time.
        
        $checkResult = $authenticator->verifyCode($secret, $otp, $tolerance);    
        
        if ($checkResult) 
        {
            echo 'OTP is Validated Succesfully';
            header('Location: admin/dashboard.php');
            exit;
        } else {
            alert("Invalid OTP. Please try again.");
        }
    }
?>
<html>
    <body>
        <form method="post">
            <p>Please enter your six digit code from Google Authenicator</p>
            <input type="password" placeholder="123456" name="code">
            <input type="submit" name="submit" id="submit" value="Submit">
        </form>
    </body>
</html>